<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Azure.Storage.Blobs" Version="12.19.1" />
      <PackageReference Include="Hangfire.AspNetCore" Version="1.8.20" />
      <PackageReference Include="Hangfire.PostgreSql" Version="1.20.12" />
      <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.3.1" />
      <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.17" />
      <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="8.0.17" />
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.8" />
      <PackageReference Include="QuestPDF" Version="2025.7.1" />
        <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="2.88.9-preview.2.2" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\AcadEvalSys.Application\AcadEvalSys.Application.csproj" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="Resources\Images\**\*" />
    </ItemGroup>

</Project>
